//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationsUsers
    {
        public int FkApplications { get; set; }
        public string FkUser { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string UrlStart { get; set; }
    
        public virtual Applications Applications { get; set; }
    }
}
